name = "DatapathVerification"
version = "0.1.0"
defaultTargets = ["DatapathVerification"]

[[lean_lib]]
name = "DatapathVerification"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"